services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    sysctls:
      net.core.somaxconn: 1024
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.0
    user: "1000:0" # Run as UID 1000 with root group
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9201:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/.aws/config:/usr/share/elasticsearch/.aws/config
    networks:
      - app-network
    entrypoint: |
      /bin/sh -c '
      mkdir -p /usr/share/elasticsearch/.aws;
      chown -R 1000:0 /usr/share/elasticsearch/.aws;
      chmod -R 750 /usr/share/elasticsearch/.aws;
      chown -R 1000:0 /usr/share/elasticsearch/config;
      chmod -R 775 /usr/share/elasticsearch/config;
      /usr/local/bin/docker-entrypoint.sh
      '
  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-backend_db}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./data/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-backend_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      postgres
      -c "listen_addresses=*"
      -c "max_connections=100"
      -c "shared_buffers=128MB"

  backend:
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-backend_db}
      - ELASTICSEARCH_URL=http://elasticsearch:9201
      - HEALTH_CHECK_TIMEOUT=${HEALTH_CHECK_TIMEOUT:-5000}
      - ELASTICSEARCH_HEALTH_TIMEOUT=${ELASTICSEARCH_HEALTH_TIMEOUT:-30000}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - PORT=3000
    build:
      context: ./backend
      dockerfile: Dockerfile

    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  # frontend:
  # container_name: frontend
  # build:
  #   context: ${FRONTEND_PATH}
  #   dockerfile: development.Dockerfile
  # ports:
  #   - "5173:3001"
  # volumes:
  #   - ${FRONTEND_PATH}:/app
  #   - /app/node_modules
  #   - /app/.next
  # healthcheck:
  #   test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/healthcheck" ]
  #   interval: 30s
  #   timeout: 10s
  #   retries: 3
  #   start_period: 160s
  # environment:
  #   - NODE_ENV=development
  #   - API_URL=api
  # networks:
  #   - app-network
  # command: npm run dev
  # depends_on:
  #   api:
  #     condition: service_healthy
volumes:
  redis-data:
  elastic-data:
  pgdata:

networks:
  app-network:
    driver: bridge
