
services:
  backend:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=warn
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
  db:
    environment:
      - POSTGRES_DB=${DB_NAME:-backend_prod}
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    
  redis:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    
  elasticsearch:
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G